#!/usr/bin/python3.7
import os,datetime,sys,time
def help():
	if sys.argv.count('-h')>0:
		print("Program do edycji dziennika, -p cofa o 1 dzien, zduplikuj -p by isc coraz dalej w tył.\n\tnp. \tdz -p -p -p\t\t edycja dziennika sprzed 3 dni\n\t\tdz\t\t\tedycja z dzisiejszego dznia\n\t\t-t\tbez daty na poczatku i koncu pliku")
		exit()

d=datetime.datetime.now()
pwd=''
def dat():
	pass
def mmm(arg=''):
	arg=str(arg)
	while len(arg)<2:
		arg='0'+arg
	return arg
def star():	
	if sys.argv.count('-r'):
		try:
			name=''
			for i in sys.argv[1:]:
				if i[0]!='-':
					name=i
					break
			if name=='':
				print(u'Błąd nazwy pliku w argumentach!!!')
				exit()
			t1=time.time()
			name=pwd+name
			os.system('vim -R '+name)
			t2=time.time()
			t2=round(t2)
			t1=round(t1)
			with open(name) as p:
				tr=p.read()
				trrr="{@"+str(t1)+'\\'+str(t2)+'}'
				try:
					if tr[:2]=='{#' or tr[:2]=='{@':
						pass
					else:
						trrr+='\n'
				except:
					trrr+='\n'
				trrr+=tr
			with open(name,'w') as p:
				p.write(trrr)
	
		except:
			print('Error na probie otwarcia pliku i pobraniu daty!')
	else:
	
		try:
			zl=sys.argv.count('-p')
			t1=time.time()
			name=pwd+str(d.year)+'.'+mmm(d.month)+'.'+mmm(d.day-zl)
			os.system('vim '+name)
			t2=time.time()
			t2=round(t2)
			t1=round(t1)
			with open(name) as p:
				tr=p.read()
				trrr="{#"+str(t1)+'\\'+str(t2)+'}'
				try:
					if tr[:2]=='{#' or tr[:2]=='{@':
						pass
					else:
						trrr+='\n'
				except:
					trrr+='\n'
				trrr+=tr
			with open(name,'w') as p:
				p.write(trrr)
	
		except:
			print('Error na probie otwarcia pliku i pobraniu daty!')



def swi(x):
	return {
		1:'styczen',
		2:'luty',
		3:'marzec',
		4:'kwiecien',
		5:'maj',
		6:'czerwiec',
		7:'lipiec',
		8:'sierpien',
		9:'wrzesien',
		10:'pazdziernik',
		11:'listopad',
		12:'grudzien'
	}[x]

def suma_kontrolna(asd):
	a=False
	nazwa=asd+'.control_sum'
	plik=open(nazwa)
	if plik.read()=='':
		a=True
	plik.close()
	return a
if __name__=='__main__':
	help()
	
	if sys.argv.count('-a')!=0:
		pwd+='/home/fredka/main/zip/p/'
		
		if os.system('cd '+pwd+'dziennik/') !=0:
			os.system('cd '+pwd+'&& ./deko')
			if suma_kontorlna(pwd+'dziennik/'):
				os.system(pwd+'./anichilacja')
				exit()
			pwd+='dziennik/'
		if suma_kontrolna(pwd):
			print(pwd+'\nWRONG PASSWD!')
			exit()
		if os.system('cd '+pwd+str(d.year))!=0:
			os.system('mkdir '+pwd+str(d.year)+'&& cd '+pwd+str(d.year))
			
		pwd+=str(d.year)+'/'
		if os.system('cd '+pwd+swi(d.month))!=0:
			os.system('mkdir '+pwd+swi(d.month)+'&& cd '+pwd+swi(d.month))
			
		pwd+=swi(d.month)+'/'

		
		

	star()


