#!/usr/bin/python3.7
import os,sys,math
ar=sys.argv
tab=''
if len(ar)>1:
	try:
		with open(ar[1]) as q:
			tab=q.read()
	except:
		print('nie ma pliku!')
		exit()
else:
	tab=input()

tab=tab.split()
for i in range(len(tab)):
	tab[i]=float(tab[i])

sr=0
for i in tab:
	sr+=i
sr/=len(tab)
print('sr: '+str(sr))
for i in range(len(tab)):
	tab[i]-=sr
	tab[i]*=tab[i]

up=0
for i in tab:
	up+=i
print('up: '+str(up))
down=0
if len(tab)>10:
	down=len(tab)*(len(tab)-1)
else:
	down=len(tab)
print('down: '+str(down))
wynik=math.sqrt(up/down)
print(wynik)
