#!/usr/bin/python3.7
import os,sys
if sys.argv.count('out'):
	if sys.argv.count('sshfs'): os.system('sshfs pi@fender.cronet.pl:/ temp')
	else: os.system('ssh pi@fender.cronet.pl')
elif sys.argv.count('ilo'):
 
	if sys.argv.count('root') and not sys.argv.count('sshfs'):
	 
	 os.system('ssh root@212.33.80.180')
	if sys.argv.count('sshfs'):
	 	os.system('sshfs root@212.33.80.180:/ ilo')
	else:
	 os.system('ssh srv-ilocamp@212.33.80.180')
else:
 
	if sys.argv.count('sshfs'): os.system('sshfs pi@192.168.1.33:/ temp')
	else: os.system('ssh pi@192.168.1.33')

