#!/usr/bin/python3.7
import os,sys
a=sys.argv
if a.count('-h') or a.count('--help'):
	print('''''')
	exit()
if len(a)>1:
	if not  a[1][0] == '-':#wszystko ok to wykonaj przeniesienie
		os.system('mv '+a[1]+' ~/.trash/')
		print(u'Przeniesiono do kosza')
		exit()
	else:
		#pass # ze nie mozna parametru uruchomic, uzyc opci -f
		print(u'''Nie można wykonać tej operacji, bo na 1. miejscu jest parametr, a nie wskazanie do pliku.
Należy wymusić przez dodanie parametru -f na końcu polecenia.''')
else:
	print(u'''Użyj parametru -h by dowiedzieć się wiecej co ten program robi''')
