#!/usr/bin/python3.7
import os,sys
co=sys.argv.count
if co('-c'):
	print('''\
#include <stdio.h>
int main(){
	return 0;
}
''')
elif not co('-p '):
	'''try:
		name=sys.argv[1]
	except:
		print('Err')
		exit()'''
	print('''\
#include <bits/stdc++.h>
#define mp make_pair
#define ff first
#define ss second
#define ll long long
#define un unsigned
using namespace std;
int main(){ios_base::sync_with_stdio(0);cin.tie(NULL);cout.tie(NULL);

}''')
	
	
