#!/usr/bin/python3.7
import os,sys,random
from time import sleep
def help():
	print(	'''

	Życzymy miłego użytkowania
	   DGE
''')
	exit()

if __name__=='__main__':
	if sys.argv.count('-h')>0:
		help()
		exit()
	import datetime
	os.system('c')
	m=0
	while 1:
		dd=(datetime.datetime(year=2018,month=9,day=28,hour=15) - datetime.datetime.now())
		d=dd.days
		s=dd.seconds
		m=s//60
		h=m//60
		m+=1
		if m>=10: 
			m=0
			os.system('c')
		#m%=60
		#h%=24
		#s%=60
		print(end='                                                                             \r')
		print('\033[91mDo spotkania z Słodziaczkiem zostało: '+str(d)+' dni, '+str(h%24)+' godzin, '+str(m%60)+' minut, '+str(s%60)+' sekund\033[0m',end='\r')
		sleep(0.5)

